apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://127.0.0.1:60047
  name: minikube
contexts:
- context:
    cluster: minikube
    user: jenkins-sa
  name: minikube
current-context: minikube
users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkVyUWU1Vk9TbDVENDVla0s2SzlnUXdoYmc5dlNVYlNacVlxOGpZeFpJdUEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzYxNDk5ODc5LCJpYXQiOjE3NjE0OTYyNzksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMTc3N2QxZjItMTIxMS00ODVhLWEwNDUtMjYxZjQ3ZGM1Y2QzIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJqZW5raW5zIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtc2EiLCJ1aWQiOiIyOTI5YzRkYi1kZTAyLTQxZjMtOGYyMC1iN2ExMjA4MjM0MjEifX0sIm5iZiI6MTc2MTQ5NjI3OSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmplbmtpbnM6amVua2lucy1zYSJ9.CQFMGJ_ilbWOUTvT2tYfIZQoyiAOgcDHmVTDPCadyZyq8C9dS-FOwGmuibE17BFHe_pgmAUkRsbV5eSfxxtTltVeXCZHEEq_Am5a3SrPLXc19HyJEyB56nOHfJBIw2YCFyy_8nC_REo4WN7hKF_mPpxMQ1VKwLMy-8G8GOYtY4fhvsNxX667ns8bxlssilbEvVGssEgqg8Ew-Ip2YSW-t_sbH1KnYr50SzeSJrJpQx4PDQaBhx_Kxsn-wUOVygM4_shFnjp4Ms-7816XdsxCd7rfne4kx6QFaNKeQwdZxkAOLBANW7K66jPxMv4lfy8kdTRHrIoM8IDlVh1z4LHCJA
