apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: med293475/mern-frontend:20  # ✅ Update to the new tag built with serve
        ports:
        - containerPort: 3000           # ✅ serve listens on 3000
        env:
        - name: VITE_API_URL
          value: "http://backend-service:5000"
        readinessProbe:
          httpGet:
            path: /
            port: 3000                  # ✅ Change probe port
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000                  # ✅ Change probe port
          initialDelaySeconds: 10
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000                   # ✅ Match serve port
  type: LoadBalancer
